language: node_js
node_js:
  - "9.8"

branches:
  only:
    - master

before_script:
- npm install --save-dev @angular/cli@latest
- npm install @angular/core
- npm install

script:
  - ng build --prod
